### ISSUE TITLE
Weight of items

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#127]
**Context** 
Each item has a unique weight. That is realistic, but it is a nuance that is not conducive to new player's understanding and not get frustrated with the game.

**Idea**
Make all items the same weight so that player's can quickly build reliable expectations of how they interact with items. In addition, I noticed that some items throw incredibly far. The new chosen weight of items I think should be similar or greater than the weight of blocks. All items should be able to be thrown off of your body, and they should all go the same distance.

**Comment by Regulator13** [comment]
I agree this is frustrating, and since jetpacks aren't as cheating as I thought, it's not that important that you not be able to throw them, and definitely not right that you can't even throw them off yourself. I will try to make most items the same weight, the only exception I can think of is trampolines, if we make it so you can grab those
