### ISSUE TITLE
How weight affects jumping ability

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#128]
**Context** 
I'm not gonna lie: with the fixing of other problems, the weight of items decreasing my jumping ability is now one of the most frustrating elements for the game. Each time I pick up an item and try to make a jump I just made, it takes me a moment to convince myself that it is actually no longer possible.

**Idea**
I would like to see it so carrying your items does not affect your jumping at all. I think that is the cleanest way to do it. However, I realize that this is jumping is a potentially important character stat. In that case, I think the impact needs to be less such that on the top end, player's with the higher strength can carry items without it having any impact at all on their jumping.

**Comment by Regulator13** [comment]
This too is a feature that disappointed me some, mostly because weight effects all players equally, no matter how strong you are. My suggestion is that the weight of the item subtracts from a base strength, then:

1. The weight is <= strength, in which case you jump normally
2. The weight is > strength, in which case you jump less

That way heavy items can be made that will slow you down unless you're very strong, but otherwise you can count on jumping normally with every other item.

**Comment by afrey15** [comment]
That would be awesome. I agree, I was excited for this feature. It just didn't bring quite as much fun as I hoped.
