### ISSUE TITLE
Player's get stuck in blocks

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire_and_ice#209]
**Bug**
Players can get stuck in a block if there is a block on top of them and another one is thrown, pushed, or grabbed to be on them as well

**Expected Behavior**
The correct behavior is not obvious but I propose we make it so players can walk behind (through) blocks if they are not frozen. This also will make it easier to get through one big block tall passageways that have block spawners in them.

**Steps to Reproduce**
1. Master
2. Any mode
3. Pick up a block, then go stand on a block spawner
4. Wait for the block to spawn on you. You'll be stuck

**Comment by afrey15** [comment]
This technically solves the problem, but unlike other bug fixes, it also changes the way the game is played. I think characters should maintain the ability to interact with blocks.

**Comment by afrey15** [comment]
Do you have any more arguments for this besides it is easier to get through low passageways?

**Comment by Regulator13** [comment]
It fixes the bug in the issue

**Comment by afrey15** [comment]
I have a few reasons for why it may not be a good idea to change this element..

**Comment by afrey15** [comment]
The proposed solution doesn't really solve the bug, it prevents the situation from occurring. If any new objects were added where we wanted physical interactive functionality, this bug would return. Blocks have been different from items because they could be pushed, used to block lasers and patrols, jumped on, and more. It is hard to mentally rectify a block that can only be stood on when it is frozen. For this issue, I would hope for a solution that adds functionality rather than taking it away.

**Comment by Regulator13** [comment]
I agree. I have proposed a solution on the chat
