### ISSUE TITLE
Make it harder to ledge hang

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#230]
**Context** 
Jumping is becoming more realistic. Ledge hanging should too

**Idea**
I have a couple ideas: First, if player's can control their jump height, we have a unique opportunity to improve ledge hanging. Right now, there is a tolerance of 5 or so pixels both up and down from the ledge. This is a massive tolerance and it is a little jumpy. My first idea is to just reduce that tolerance significantly, or entirely depending on the tolerance it allows. This will mean that players moving very fast can't catch the ledge, which is realistic, and it eliminates the jumpiness all at once. My second idea is also simple: you must face the direction of the ledge. 

**Reasoning**
Right now, ledges are magnets. You just latch onto them. This will make a ledge grab more satisfying and realistic.

**Comment by Regulator13** [comment]
I can reduce the tolerance but I suggest we keep the facing either way since direction is not always intuitive or necessarily the direction your moving.

**Comment by afrey15** [comment]
It should be with the new jumps though..

**Comment by Regulator13** [comment]
No, but since you can't change directions in air it will be impossible to land a backward ledge grab anyway. The current tolerance for the ledge is 5 pixels. What do you want it to be?

**Comment by afrey15** [comment]
It should be impossible to land a backward ledge grab but sometimes weird situations arise. It would be good to have that check and make sure the player is facing the direction of the ledge. I have enjoyed ledge magnets as much as the rest of us but I am excited to move on as well

**Comment by Regulator13** [comment]
I get what you're saying but I'm not sure if this will work like you want it to. Lower tolerance would make it harder at higher speeds (Although I think 1 or 2 is too low) but player's would still be able to grab the ledge at a speed of 10. It would just be up to luck if their tenth pixel happens to land in the tolerance. If this is really all about the speed, I could just have the script check their `vspeed` and keep the tolerance.

FYI the players currently set their `vspeed` to ~6 every step they press down on up. But I don't think player's will adjust the height of their jump to grab. The small jump doesn't even bring them out of the mandatory space they must have below themselves to grab a ledge. The change would really be more for falling

I wouldn't have to add a check for the backward ledge grab, I jut added a check to allow it in the current pull request. The reason for this is because a player can be jumping right at a ledge but if they happen to have their mouse behind them they will not grab the ledge which I thought was annoying

**Comment by afrey15** [comment]
Interesting. That reveals a different problem. None of our other firing inputs have control over the direction of the character. I think that the character should face the direction he is traveling, not the direction he is pointing to shoot (as it is in the other inputs). Then we can remove this check. I see what you are saying about luck. A vspeed check would be good but I'd like to reduce the tolerance still because it was even more about the character transporting than it was about realism.

**Comment by Regulator13** [comment]
I will reduce the tolerance and add a vspeed check in. The characters direction is used a lot in aiming to decide which direction the bullets will fly so it doesn't really work to just have them face the direction they're moving.

**Comment by afrey15** [comment]
Is this the case with joysticks as well? I would be interested in exploring an option where the player's shooting range is limited to the 180 degrees of the direction they are currently facing.

**Comment by Regulator13** [comment]
With the exception of the gamepad, it is limited to the 180 degree they're facing.
