### ISSUE TITLE
Down key to fall faster

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#231]
**Context** 
Okay this one isn't realistic, but Isaiah inspired the idea for me and I think it could be fun.

**Idea**
Press down key while in the air to increase your falling speed up to your max gravity.

**Reasoning**
Because you can bounce on a trampoline and hold down to bounce faster and harder than ever before. It's like trampoline bouncing 2.0. Could also be useful in other situations I suppose..

**Comment by Regulator13** [comment]
This really baffles me. All I can think is we just added a bunch of realism and this is really out of line. So I'll try and give an overwhelming number of reasons to not add this issue:

1. We just added variable jump height to make player's think, but if I can just press down to go down, I'm gonna jump full height every time and then smash the down key so I don't have to think.
2. Similarly we just reduced drag, which also wouldn't mean much if you could just push yourself into the ground instead of timing your jumps.
3. I think the main reason you want it is because it takes a while to reach full height on a trampoline, but:
   - That is natural and realistic for a trampoline
   - It is 100% intended skill-wise, There are lots of things that take more time than they need: spawning a block, freezing a block, using a trampoline. There are all intended because this game is all about time. It encourages players to find smarter solution than bounce on the trampoline and freeze blocks all the way up. Slowing down climbing was a great change because before you could complete the whole level with 1 item.

In conclusion, please no.

**Comment by afrey15** [comment]
These are the best arguments you've ever provided.
